export const buses = [
  {
    Departure: "coimbatore",
    Arrival: "bangalore",
    Dtime: "23:35",
    Atime: "08:20",
    Duration: "08:45",
    name: "TNSTC",
    price: 768,
    rating: 4.4,
    type: "AC MULTIAXLE - 1505TVMBNG",
    Available: 16,
  },
  {
    Departure: "coimbatore",
    Arrival: "bangalore",
    Dtime: "02:10",
    Atime: "07:00",
    Duration: "04:50",
    name: "YATHRA LOGISTICS",
    price: 1599,
    rating: 4.6,
    type: "AC Sleeper (2 + 1)",
    Available: 32,
  },
  {
    Departure: "coimbatore",
    Arrival: "bangalore",
    Dtime: "17:30",
    Atime: "23:59",
    Duration: "06:29",
    name: "ORANGE TOURS",
    price: 1500,
    rating: 4.7,
    type: "SCANIA AC Multi Axle Sleeper (2 + 1)",
    Available: 13,
  },
  {
    Departure: "bangalore",
    Arrival: "coimbatore",
    Dtime: "22:50",
    Atime: "06:00",
    Duration: "07:10",
    name: "INTERCITY SMARTBUS",
    price: 1190,
    rating: 4.8,
    type: "AC Sleeper (2 + 1)",
    Available: 30,
  },
  {
    Departure: "bangalore",
    Arrival: "coimbatore",
    Dtime: "23:00",
    Atime: "04:45",
    Duration: "05:45",
    name: "GREENLINE TRAVELS",
    price: 1600,
    rating: 4.6,
    type: "AC Sleeper (2 + 1)",
    Available: 27,
  },
  {
    Departure: "bangalore",
    Arrival: "coimbatore",
    Dtime: "20:45",
    Atime: "05:00",
    Duration: "08:15",
    name: "A1 TRAVELS",
    price: 600,
    rating: 4.3,
    type: "NON-AC Seater/Sleeper (2 + 1)",
    Available: 45,
  },
  {
    Departure: "chennai",
    Arrival: "bangalore",
    Dtime: "23:30",
    Atime: "06:00",
    Duration: "06:30",
    name: "SPS TRAVELS",
    price: 1500,
    rating: 4.4,
    type: "A/C Sleeper (2+1)",
    Available: 26,
  },
  {
    Departure: "chennai",
    Arrival: "bangalore",
    Dtime: "21:00",
    Atime: "06:49",
    Duration: "09:49",
    name: "YOLO BUS",
    price: 799,
    rating: 4.7,
    type: "A/C Sleeper (2+1)",
    Available: 20,
  },
  {
    Departure: "bangalore",
    Arrival: "madurai",
    Dtime: "18:00",
    Atime: "04:00",
    Duration: "10:00",
    name: "ROYAL TRAVELS",
    price: 1050,
    rating: 4.4,
    type: "NON-AC Seater/Sleeper (2 + 1)",
    Available: 25,
  },
];
